---
- name: Install base packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Set the system timezone
  community.general.timezone:
    name: "{{ common_timezone }}"
