"""initial schema

Revision ID: 8011c58c0251
Revises: 
Create Date: 2026-09-24 20:03:13.540814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from falcoria_scanledger.events.models import Xid8
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8011c58c0251'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('port_prevalence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 1', name='ck_port_prevalence_score_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'protocol')
    )
    op.create_index(op.f('ix_port_prevalence_number'), 'port_prevalence', ['number'], unique=False)
    op.create_index(op.f('ix_port_prevalence_protocol'), 'port_prevalence', ['protocol'], unique=False)
    op.create_index(op.f('ix_port_prevalence_score'), 'port_prevalence', ['score'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('hashed_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ip_port_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('observed_state', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ip', 'port', 'protocol', 'change_type', 'created_at')
    )
    op.create_index(op.f('ix_ip_port_history_ip'), 'ip_port_history', ['ip'], unique=False)
    op.create_index(op.f('ix_ip_port_history_project_id'), 'ip_port_history', ['project_id'], unique=False)
    op.create_index('ix_ip_port_history_project_id_created_at', 'ip_port_history', ['project_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_ip_port_history_scan_id'), 'ip_port_history', ['scan_id'], unique=False)
    op.create_table('ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('first_seen', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'project_id')
    )
    op.create_index(op.f('ix_ips_ip'), 'ips', ['ip'], unique=False)
    op.create_index(op.f('ix_ips_project_id'), 'ips', ['project_id'], unique=False)
    op.create_table('observed_hostnames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname', 'project_id')
    )
    op.create_index(op.f('ix_observed_hostnames_hostname'), 'observed_hostnames', ['hostname'], unique=False)
    op.create_index(op.f('ix_observed_hostnames_project_id'), 'observed_hostnames', ['project_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('txid', Xid8(), server_default=sa.text('pg_current_xact_id()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_outbox_events_project_id_txid_id', 'outbox_events', ['project_id', 'txid', 'id'], unique=False)
    op.create_table('project_member_link',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_index(op.f('ix_project_member_link_user_id'), 'project_member_link', ['user_id'], unique=False)
    op.create_table('observed_hostname_ip_link',
    sa.Column('ip_id', sa.Integer(), nullable=False),
    sa.Column('hostname_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hostname_id'], ['observed_hostnames.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ip_id'], ['ips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ip_id', 'hostname_id')
    )
    op.create_index(op.f('ix_observed_hostname_ip_link_hostname_id'), 'observed_hostname_ip_link', ['hostname_id'], unique=False)
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('extrainfo', sa.String(), nullable=True),
    sa.Column('cpe', sa.JSON(), nullable=True),
    sa.Column('servicefp', sa.String(), nullable=True),
    sa.Column('service_method', sa.String(), nullable=True),
    sa.Column('service_confidence', sa.Integer(), nullable=True),
    sa.Column('tunnel', sa.String(), nullable=True),
    sa.Column('scripts', sa.JSON(), nullable=True),
    sa.Column('ip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ip_id'], ['ips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'protocol', 'ip_id')
    )
    op.create_index(op.f('ix_ports_ip_id'), 'ports', ['ip_id'], unique=False)
    op.create_index(op.f('ix_ports_number'), 'ports', ['number'], unique=False)
    op.create_index(op.f('ix_ports_product'), 'ports', ['product'], unique=False)
    op.create_index(op.f('ix_ports_protocol'), 'ports', ['protocol'], unique=False)
    op.create_index(op.f('ix_ports_service'), 'ports', ['service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ports_service'), table_name='ports')
    op.drop_index(op.f('ix_ports_protocol'), table_name='ports')
    op.drop_index(op.f('ix_ports_product'), table_name='ports')
    op.drop_index(op.f('ix_ports_number'), table_name='ports')
    op.drop_index(op.f('ix_ports_ip_id'), table_name='ports')
    op.drop_table('ports')
    op.drop_index(op.f('ix_observed_hostname_ip_link_hostname_id'), table_name='observed_hostname_ip_link')
    op.drop_table('observed_hostname_ip_link')
    op.drop_index(op.f('ix_project_member_link_user_id'), table_name='project_member_link')
    op.drop_table('project_member_link')
    op.drop_index('ix_outbox_events_project_id_txid_id', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_observed_hostnames_project_id'), table_name='observed_hostnames')
    op.drop_index(op.f('ix_observed_hostnames_hostname'), table_name='observed_hostnames')
    op.drop_table('observed_hostnames')
    op.drop_index(op.f('ix_ips_project_id'), table_name='ips')
    op.drop_index(op.f('ix_ips_ip'), table_name='ips')
    op.drop_table('ips')
    op.drop_index(op.f('ix_ip_port_history_scan_id'), table_name='ip_port_history')
    op.drop_index('ix_ip_port_history_project_id_created_at', table_name='ip_port_history')
    op.drop_index(op.f('ix_ip_port_history_project_id'), table_name='ip_port_history')
    op.drop_index(op.f('ix_ip_port_history_ip'), table_name='ip_port_history')
    op.drop_table('ip_port_history')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_port_prevalence_score'), table_name='port_prevalence')
    op.drop_index(op.f('ix_port_prevalence_protocol'), table_name='port_prevalence')
    op.drop_index(op.f('ix_port_prevalence_number'), table_name='port_prevalence')
    op.drop_table('port_prevalence')
    # ### end Alembic commands ###
